### ISSUE TITLE
Support for create/update/destroy?

### ISSUE THREAD

**Issue by jordaaash** [sequiturs/bookshelf-advanced-serialization#8]
Nice work on this, thank you!

Do you have plans to handle writes as well, or just keep the scope of the project to reads?

It seems like you use this in production already -- how does Sequiturs currently handle access control for writes?

**Comment by ihinsdale** [comment]
Thanks!

I do use this in production, in tandem with another plugin that handles access control for write operations. I'm definitely going to open-source that other plugin once the API is stable. 

I'm going to keep the scope of this plugin limited to reads/serialization, so that via `roleDeterminer` it's agnostic about how the application wants to implement access control. That's also in the interest of doing one thing well.

But the other plugin that I've written integrates nicely with this one and actually spares you from having to define `roleDeterminer` at all, since it can just rely on the way you've defined granting the `read` permission. Will let you know when that plugin is available!

**Comment by jordaaash** [comment]
Cool, thank you very much! Looking forward to it.

**Comment by ihinsdale** [comment]
@jordansexton 

As promised, this is a heads-up that the other plugin supporting access control for CRUD operations is now available: [bookshelf-permissions](https://github.com/sequiturs/bookshelf-permissions)

Hope it's useful to you, and let me know if you have any questions about how to use it.

**Comment by jordaaash** [comment]
@ihinsdale Finally catching up and checking this out now. Thanks for releasing and letting me know! Your work is appreciated.
